# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # TODO: Update to 5.12.x once we drop Python3.7 support
  # https://levelup.gitconnected.com/fix-runtimeerror-poetry-isort-5db7c67b60ff
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
 # TODO: add black formatting
 # - repo: https://github.com/psf/black
 #   rev: 23.1.0
 #   hooks:
 #     - id: black
